#!/bin/bash

echo 'Starting tests...'

FAIL=0

CHROMEDRIVER_URL=http://localhost:9516 bundle exec rspec --tag media spec/integration_spec.rb &
CHROMEDRIVER_URL=http://localhost:9517 bundle exec rspec --tag sources spec/integration_spec.rb &
CHROMEDRIVER_URL=http://localhost:9518 bundle exec rspec --tag search spec/integration_spec.rb &
CHROMEDRIVER_URL=http://localhost:9519 bundle exec rspec --tag users spec/integration_spec.rb &
CHROMEDRIVER_URL=http://localhost:9520 bundle exec rspec --tag annotation spec/integration_spec.rb &
CHROMEDRIVER_URL=http://localhost:9521 bundle exec rspec --tag other spec/integration_spec.rb &

for job in `jobs -p`
do
  echo $job
  wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
  exit 0
else
  exit 1
fi
