#!/usr/bin/ruby
require 'pty'
threads = []
exitcode = 0
tags = ''
#['--tag sources --tag search --tag users', '--tag annotation --tag media --tag other'].each do |tags|
#  threads << Thread.new do
    cmd = "bundle exec rspec #{tags} spec/integration_spec.rb"
    begin
      PTY.spawn(cmd) do |stdout, stdin, pid|
        begin
          stdout.each { |line| print line }
        rescue Errno::EIO
        end
        Process.wait(pid)
      end
      exitcode = 1 if $?.exitstatus > 0
    rescue PTY::ChildExited
    end
#  end
#end
#threads.each do |thread|
#  thread.join
#end
exit exitcode
