version: "2.2"
networks:
  default:
    name: dev
services:
  chromedriver:
    build: chromedriver
    environment:
      SE_NODE_MAX_SESSIONS: 12
      SE_NODE_SESSION_TIMEOUT: 120
    ports:
      - 5900:5900
      - 4444:4444
    volumes:
      - "./test/spec/files:/app/test/spec/files"
      - "./check-ui/.yalc:/root/.yalc"
    networks:
      - dev
  api:
    environment:
      RAILS_ENV: test
      PAPERTRAIL_ENABLED: "true"
      SERVER_PORT: 3000
  api-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3000
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: bogus
      AWS_ACCESS_KEY_ID: bogus
      SECRET_KEY_BASE: bogus
  pender:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  pender-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  alegre:
    environment:
      BOILERPLATE_ENV: test
      ALEGRE_PORT: 3100
  presto-server:
    environment:
      BOILERPLATE_ENV: test
      PRESTO_PORT: 8000
  presto-audio:
    environment:
      BOILERPLATE_ENV: test
  presto-image:
    environment:
      BOILERPLATE_ENV: test
  presto-video:
    environment:
      BOILERPLATE_ENV: test
  web:
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: test
