version: "2.2"
networks:
  default:
    name: dev
services:
  chromedriver:
    build: chromedriver
    ports:
      - 5900:5900
      - 4444:4444
    volumes:
      - "./test/spec/files:/app/test/spec/files"
      - "./check-ui/.yalc:/root/.yalc"
    networks:
      - dev
  api:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3000
  api-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3000
  pender:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  pender-background:
    environment:
      RAILS_ENV: test
      SERVER_PORT: 3200
  alegre:
    environment:
      BOILERPLATE_ENV: test
      ALEGRE_PORT: 5000
  web:
    depends_on:
      - chromedriver
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: test
