#!/usr/bin/env node

const port = 3333;

var util = require('util');

var http = require('http'),
    finalhandler = require('finalhandler'),
    serveStatic = require('serve-static'),
    serve = serveStatic('build/web');

var server = http.createServer(function(req, res) {
  var done = finalhandler(req, res);
  serve(req, res, done);
});

// Local server

server.listen(port);
console.log('Webserver running locally at http://localhost:' + port);

// Remote server

var spawn = require('child_process').spawn;
var child = spawn('ngrok', ['http', port, '-log', 'stdout', '--log-level', 'debug']);
var gotUrl = false;
child.stdout.on('data', function(chunk) {
  var output = chunk.toString();
  if (!gotUrl && /URL:/.test(output)) {
    gotUrl = true;
    var url = output.replace(/.*URL:([^ ]+) .*/, "$1");
    console.log('Webserver running publicly at ' + url);
  }
});
