#!/usr/bin/env node

const port = 3333;

// Local server

var express = require('express'),
    serveStatic = require('serve-static'),
    app = express();
app.use(serveStatic('build/web', { 'index': ['index.html'] }))
app.use(function(req, res, next) {
  res.sendFile(process.cwd() + '/build/web/index.html');
});
app.listen(port)
console.log('Webserver running locally at http://localhost:' + port);

// Remote server

var spawn = require('child_process').spawn;
var child = spawn('ngrok', ['http', port, '-log', 'stdout', '--log-level', 'debug']);
var gotUrl = false;
child.stdout.on('data', function(chunk) {
  var output = chunk.toString();
  if (!gotUrl && /URL:/.test(output)) {
    gotUrl = true;
    var url = output.replace(/.*URL:([^ ]+) .*/, "$1");
    console.log('Webserver running publicly at ' + url);
  }
});
