name: Build and Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - develop

jobs:
  media-similarity-tests:
    if: >
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/master' ||
      contains(github.event.head_commit.message, '[full ci]') ||
      contains(github.event.head_commit.message, '[media similarity tests]')
    continue-on-error: true
    uses: ./.github/workflows/reusable-test-setup.yaml
    with:
      test_type: media-similarity-tests
    secrets: inherit

  text-similarity-tests:
    if: >
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/master' ||
      contains(github.event.head_commit.message, '[full ci]') ||
      contains(github.event.head_commit.message, '[text similarity tests]')
    continue-on-error: true
    uses: ./.github/workflows/reusable-test-setup.yaml
    with:
      test_type: text-similarity-tests
    secrets: inherit

  integration-and-unit-tests:
    if: >
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/master' ||
      contains(github.event.head_commit.message, '[full ci]') ||
      contains(github.event.head_commit.message, '[smoke tests]')
    uses: ./.github/workflows/reusable-test-setup.yaml
    with:
      test_type: integration-and-unit-tests
    secrets: inherit

  unit-tests:
    if: >
      github.ref != 'refs/heads/develop' &&
      github.ref != 'refs/heads/master' &&
      !contains(github.event.head_commit.message, '[full ci]') &&
      !contains(github.event.head_commit.message, '[smoke tests]') &&
      !contains(github.event.head_commit.message, '[media similarity tests]') &&
      !contains(github.event.head_commit.message, '[text similarity tests]')
    uses: ./.github/workflows/reusable-test-setup.yaml
    with:
      test_type: unit-tests
    secrets: inherit
